# Generated by Django 5.0.14 on 2025-07-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apptransformation", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("member", "Member")],
                default="member",
                max_length=10,
            ),
        ),
    ]
